version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  # redis:
  #   container_name: redis
  #   image: redis/redis-stack
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
  #   # environment:
  #   #   REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
  #   volumes:
  #     - redis-data:/data

  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - prometheus-data:/prometheus
  #     - ./config/prometheus:/etc/prometheus

volumes:
  pg-data:
  # prometheus-data:
  # redis-data:
